#!/bin/bash

echo "${RED}${HIGHLIGHT}Script Running On the Remote Server Now ${NC}"

# download and upload to remote automaticlly

# ziped with passoword and uploaded to transfer.sh

# to local

# data pipeline

# TODO: local sync and remote sync process