#!/bin/bash

echo "${RED}${HIGHLIGHT}Script Running On the Remote Server Now ${NC}"

# use build to run demo code quickly
# mainly focus on build script in github
BASEDIR="/home/ubuntu/"

install_dict() {
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"
    cd dict
    git clone https://github.com/1N3/IntruderPayloads &
    git clone https://github.com/Bo0oM/fuzz.txt &
    git clone https://github.com/gh0stkey/Web-Fuzzing-Box &
    git clone https://github.com/payloadbox/xxe-injection-payload-list &
    echo "${GREEN}[Succeed]${NC}: Installed Successful"
}

install_bounty_domain(){
    echo "Get Bounty Domains"
}

install_scan(){
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    echo "[Info]: Starting to install subDomainsBrute"
    cd scantools
    python3 -m venv scanenv && source scanenv/bin/activate 
    pip3 install aiodns # for subDomainBrute
    git clone https://github.com/lijiejie/subDomainsBrute

    echo "[Info]: Starting to install Sublist3r"
    git clone https://github.com/aboul3la/Sublist3r
    pip3 install -q -r Sublist3r/requirements.txt

    echo "[Info]: Starting to install dirsearch"
    git clone https://github.com/maurosoria/dirsearch.git
    pip3 install -q -r dirsearch/requirements.txt
    
    echo "[Info]: Starting to install dirmap"
    git clone https://github.com/H4ckForJob/dirmap.git
    pip3 install -q -r dirmap/requirement.txt
    
    echo "[Info]: Starting to install dirdar"
    wget -q -O DirDar.zip https://github.com/M4DM0e/DirDar/releases/download/v1.0.0/DirDarV1.0-linux64.zip
    unzip DirDar.zip && sudo mv releases/dirdar /usr/local/bin

    echo "[Info]: Starting to install whatwaf"
    git clone https://github.com/Ekultek/WhatWaf/
    pip3 install -q -r WhatWaf/requirements.txt

    echo "[Info]: Starting to install CMSeek"
    git clone https://github.com/Tuhinshubhra/CMSeeK
    pip3 install -q -r CMSeeK/requirements.txt

    echo "[Info]: Starting to install XSStrike"
    git clone https://github.com/s0md3v/XSStrike
    pip3 install -q -r XSStrike/requirements.txt

    echo "[Info]: Starting to install vulscan"
    git clone https://github.com/scipag/vulscan scipag_vulscan
    sudo ln -s `pwd`/scipag_vulscan /usr/share/nmap/scripts/vulscan    

    echo "[Info]: Starting to install XrayScan"
    wget -q -O xray.zip https://github.com/chaitin/xray/releases/download/1.8.4/xray_linux_amd64.zip
    unzip xray.zip
    sudo mv xray_linux_amd64 /usr/local/bin/xray
    # git clone https://github.com/epsylon/xsser
    # sudo apt-get install -y python3-pycurl python3-bs4 python3-geoip python3-gi python3-cairocffi python3-selenium firefoxdriver

    echo "[Info]: Starting to install is-website-vulnerable"
    sudo docker pull lirantal/is-website-vulnerable:latest

    echo "[Info]: Starting to install naabu"
    sudo apt install -y libpcap-dev
    wget -q -O naabu.zip https://github.com/projectdiscovery/naabu/releases/download/v2.0.5/naabu_2.0.5_linux_amd64.zip
    unzip naabu.zip && sudo mv naabu /usr/local/bin/
    
    echo "[Info]: Starting to install fuploider（upload scan)"
    git clone https://github.com/almandin/fuxploider
    pip install -r fuxploider/requirements.txt

    echo "[Info]: Starting to install Corsy(cors scan)"
    git clone https://github.com/s0md3v/Corsy
    pip install -r Corsy/requirements.txt

    echo "[Info]: Starting to install log4j scan"
    git clone https://github.com/fullhunt/log4j-scan
    pip install -r log4j-scan/requirements.txt

    echo "[Info]: Starting to install rapid scan"
    git clone https://github.com/skavngr/rapidscan


    echo "${GREEN}[Succeed]${NC}: Installed Successful"

}

install_fuzz(){
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    cd ~/fuzz
    rm -rf ./*

    python3 -m venv fuzzenv
    source fuzzenv/bin/activate
    
    echo "[Info]: Starting to install ffuf"

    wget -q -O ffuf.tar.gz https://github.com/ffuf/ffuf/releases/download/v1.3.1/ffuf_1.3.1_linux_amd64.tar.gz
    tar -xf ffuf.tar.gz
    sudo mv ffuf /usr/local/bin/
    
    # echo "[Info]: Starting to install Peach"
    # sudo apt-get -y install libxml2-dev libxslt1-dev lib32z1-dev
    # git clone --depth 1 https://github.com/mozillasecurity/peach
    # git clone --depth 1 https://github.com/mozillasecurity/fuzzdata
    # mv fuzzdata peach
    # pip3 install -q -r peach/requirements.txt

    echo "[Info]: Starting to install Grizzly"
    pip3 install -q ffpuppet fuzzfetch 
    pip3 install -q grizzly-framework

    mkdir browsers
    python3 -m fuzzfetch --asan --name firefox --fuzzing -o ./browsers/

    python3 -m pip install prefpicker --user
    python3 -m prefpicker browser-fuzzing.yml ~/fuzz/prefs.js

    echo "[Info]: Starting to install domato"
    git clone https://github.com/googleprojectzero/domato

    mkdir domato_adapter
    wget -q -O domato_adapter/domato.py https://gist.githubusercontent.com/mylamour/375aaa58ff302e48f6e1881013dd6094/raw/898d20c984f442bc31e02dd7962248a2a95f32d6/domato.py
    wget -q -O domato_adapter/setup.py https://gist.githubusercontent.com/mylamour/375aaa58ff302e48f6e1881013dd6094/raw/57674bbd38379799525460f81a4406f1940e8ea5/setup.py

    python3 -m pip install -e domato_adapter

    install_dict
    echo "${GREEN}[Succeed]${NC}: Installed Successful"

}

install_dataleak(){
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"
    
    cd dataleak
    python3 -m venv leakenv && source leakenv/bin/activate 

    git clone https://github.com/UnkL4b/GitMiner
    pip3 install -q -r GitMiner/requirements.txt
    
    git clone https://github.com/wuseman/EMAGNET && chmod +x EMAGNET/emagnet.sh
    
    git clone https://github.com/jordanpotti/AWSBucketDump
    pip3 install -q -r AWSBucketDump/requirements.txt
    
    echo "${GREEN}[Succeed]${NC}: Installed Successful"
}

isntall_toolx(){    
    echo "[Info]: Starting to install offensive-docker"
    sudo docker pull aaaguirrep/offensive-docker
    
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    git clone https://github.com/rajkumardusad/Tool-X.git
    cd Tool-X
    chmod +x install
    printf 'Y\n' | ./install
    echo "${GREEN}[Succeed]${NC}: Installed Successful"
}

install_platform() {
    # rengine was all in one platform
    cd allinoneplatform
    
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    echo "[Info]: Starting to install rengine"
    # will install docker automatically
    sudo rm -rf rengine
    git clone https://github.com/yogeshojha/rengine && cd rengine

    authpass=$(pwgen -s -1 18)
    pgpass=$(pwgen -s -1 18)

    sed -i "s/AUTHORITY_PASSWORD=.*/AUTHORITY_PASSWORD=$authpass/g" .env
    sed -i "s/POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$pgpass/g" .env
    sed -i '/make username/d' install.sh

    chmod +x ./install.sh && sudo ./install.sh

    # # If have backup file, then restore 
    if [ -f '/tmp/rengine_dump.sql' ]; then
        echo "[Info]: Starting to restore data"
        sudo docker stop rengine_web_1
        sudo docker exec -i rengine_db_1 psql -U rengine postgres -c "DROP DATABASE rengine;"
        sudo docker exec -i rengine_db_1 psql -U rengine postgres -c "CREATE DATABASE rengine;"
        cat /tmp/rengine_dump.sql | sudo docker exec -i rengine_db_1 psql -U rengine -d rengine
        sudo docker exec -i rengine_db_1 psql -U rengine postgres -c "ALTER USER rengine PASSWORD '${pgpass}';"
        sudo make build 
        sudo make up
    fi

    # # use  ·make username· to create user
    # echo "[Info]: Starting to install sn1per"
    # sudo docker pull xer0dayz/sn1per 
    # echo "${GREEN}[Succeed]${NC}: Installed Successful"
}

install_proxy() {
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    echo "[Info]: Get Proxy List" 
    # Download and save to local file `proxt-list.txt` with format `IP:PORT`
    curl -sSf "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt" > proxy-list.txt

    echo "[Info]: Starting to install zap"
    # need java runtime
    wget -q -O zap.tar.gz https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
    tar -xf zap.tar.gz
    if ! command -v java &>/dev/null; then
        echo "[Warning] java env not found, let's install"
        sudo bash /tmp/runtime java
    fi

    sudo docker run -d -p 8899:8899 -p 8081:8081 -v /var/www/scylla:/var/www/scylla wildcat/scylla:latest

    echo "[Info]: Starting to install hetty"
    wget -q -O hetty.tar.gz https://github.com/dstotijn/hetty/releases/download/v0.6.0/hetty_0.6.0_Linux_x86_64.tar.gz
    tar -xf hetty.tar.gz
    echo "${GREEN}[Succeed]${NC}: Installed Successful"

}

install_osint(){

    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    echo "[Info]: Starting to install ghunt"
    git clone https://github.com/mxrch/ghunt
}

install_mobsf(){
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"

    git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
    # cd Mobile-Security-Framework-MobSF
    # sudo docker build -t mobsf .
    # sudo docker run -it --rm -p 8000:8000 mobsf 

    echo "${GREEN}[Succeed]${NC}: Installed Successful"
}

install_xrdp() {
    # TODO: need to test and change xrdp password and change root password
    # NOTE: 2c/4g at least , extreme slowly
    echo "[Info]: Starting to ${FUNCNAME[0]/_/ }"
    sudo apt-get update
    sudo apt-get install -y xfce4 xfce4-goodies xrdp xfconf
    sudo adduser xrdp ssl-cert
    sudo systemctl restart xrdp
    echo "startxfce4" > ~/.Xsession
    chmod +x ~/.Xsession
    sudo systemctl restart xrdp.service

    # echo 'user:passwd' | sudo chpasswd
    # there was a script wget https://www.c-nergy.be/downloads/xrdp-installer-1.2.2.zip
    # printf '2\n' | sudo apt-get install -y ubuntu-desktop 
    #  use lightdm
    # X -configure && X -config /root/xorg.conf.new &


    # sudo mv /root/xorg.conf.new /etc/X11/xorg.conf
    # docker run -p 0.0.0.0:6080:80 -e USER=doro -e PASSWORD=password -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc:focal
}

if [ ! -z ${1} ]; then
    case ${1} in
    'allin')

        for i in $(typeset -f | awk '/ \(\) $/ && !/^main / {print $1}'); do
            eval $i
        done

        ;;
    'fuzz')
        install_fuzz
        ;;
    'dict')
        install_dict
        ;;
    'proxy')
        install_proxy
        ;;
    'toolx')
        isntall_toolx
        ;;
    'dataleak')
        install_dataleak
        ;;
    'platform')
        install_platform
        ;;
    'xrdp')
        install_xrdp
        ;;
    'mobsf')
        install_mobsf
        ;;
    'scan')
        install_scan
        ;;
    *)
        echo "${RED}${HIGHLIGHT}[Error]${NC}: $1 was not included"
        echo "Supported:"
        typeset -f | awk '/ \(\) $/ && !/^main / {print $1}'
        ;;
    esac
fi