#!/bin/bash

echo "${RED}${HIGHLIGHT}Script Running On the Remote Server Now ${NC}"

assets_pipeline() {
    mkdir -p ~/mdata/$domainname
    # find sub domain & path
    if [ ! -d "scantools" ]; then
        echo "${RED}${HIGHLIGHT}[Warning]${NC}: your tools folder was not exists, please use $(./start.sh -m tools scan) to initialize it"
        exit 1
    else
        if [ ! -f ~/mdata/$domainname/$domainname.lists.ips ]; then
            echo "+Assests"
            cd ~/scantools/subDomainsBrute && python3 subDomainsBrute.py --w --full $domainname --output ~/mdata/$domainname/$domainname.lists.domainswithip
            cat ~/mdata/$domainname/$domainname.lists.domainswithip | awk '{print $1}' >~/mdata/$domainname/$domainname.lists.domain
            cat ~/mdata/$domainname/$domainname.lists.domainswithip | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | uniq >~/mdata/$domainname/$domainname.lists.ips
        fi
    fi
}

# Focused on Workflow
scan_pipeline() {

    source ~/scantools/scanenv/bin/activate
    echo "${GREEN}[Info]${NC}: Scan Environment Activated"
    echo "Domain: $domainname"

    cat ~/mdata/$domainname/$domainname.lists.ips | sudo naabu >~/mdata/$domainname/$domainname.lists.ports
    nmap -sV --script=vulscan/vulscan.nse

    echo "3. url path check with dirsearch"
    cd ~/scantools/dirsearch/ && python3 dirsearch.py --url-list ~/mdata/$domainname/$domainname.lists.domain --output ~/mdata/$domainname/$domainname.lists.urlswithstatus >/dev/null
    # echo "3. url path check with dirmap"
    # cd ~/scantools/dirsearch/ && python3 dirmap.py -iF ~/mdata/$domainname/$domainname.lists.domain -lcf >/dev/null

    # echo "4. waf detection"
    # cat ~/mdata/$domainname/$domainname.lists.urlswithstatus | awk '{print $3}' >~/mdata/$domainname/$domainname.lists.urls
    # cd ~/scantools/WhatWaf/ && python3 whatwaf --list ~/mdata/$domainname/$domainname.lists.urls --output ~/mdata/$domainname/$domainname.lists.wafcheck

    # vuln scan

    # echo "5. cms detection"
    # cd ~/scantools/CMSeeK/ && python3 cmseek.py --list ~/mdata/$domainname/$domainname.lists.urls

    # WAF  detection
}

fuzz_pipeline() {
    echo "[Info]: Starting to fuzz"
    if [ ! -f ~/fuzz/prefs.js ]; then
        echo "${RED}${HIGHLIGHT}[Error]${NC}: fuzz tools was not installed, please run `./start.sh -m tools fuzz`"
        exit 1
    fi
    cd ~/fuzz
    source fuzzenv/bin/activate
    nohup python3 -m grizzly ./browsers/firefox/firefox do-ma --xvfb &
    
    echo "${GREEN}[Succeed]${NC}: Runing in background"
    # ffuf  -w fuzz.txt -u FUZZ -mc all -fs 42 -c -v
}

if [ ! -z ${1} ]; then
    case ${1} in
    'scan')
        domainname=${2}
        scan_pipeline
        ;;
    'fuzz')
        fuzz_pipeline
        ;;
    *)
        echo "${RED}${HIGHLIGHT}[Error]${NC}: $1 was not included"
        echo "Supported:"
        typeset -f | awk '/ \(\) $/ && !/^main / {print $1}'
        ;;
    esac
fi
