#!/bin/bash

# RED='\e[91m'
# GREEN='\e[92m'
# YELLOW='\e[93m'
# NC='\e[0m'
# _red() { echo -e ${RED}$*${NC}; }
# _green() { echo -e ${GREEN}$*${NC}; }
# _yellow() { echo -e ${YELLOW}$*${NC}; }



# cat <<EOF > ~/.bashrc 
# export RED="tput setaf 1"
# export GREEN="tput setaf 2"
# export YELLOW="tput setaf 2"
# export NC="tput sgr0"
# EOF


echo "[Info]: Starting to modifie .bashrc"

sed -i '$ a export RED="tput setaf 1"' ~/.bashrc 
sed -i '$ a export GREEN="tput setaf 2"' ~/.bashrc 
sed -i '$ a export YELLOW="tput setaf 2"' ~/.bashrc 
sed -i '$ a export NC="tput sgr0"' ~/.bashrc 

source ~/.bashrc
echo "${GREEN}[Info]${NC}: Modified Successful"

# Install Building Essential and Basic Tools
echo "${YELLOW}[Info]${NC}: Starting to install essential"
sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y build-essential curl tmux git unzip lynx pandoc python3 python3-pip python3-tqdm >/dev/null 2>&1
curl -s https://rclone.org/install.sh | sudo bash >/dev/null 2>&1
echo "${GREEN}[Info]${NC}: Installed Successful"

echo "${YELLOW}[Info]${NC}: Starting to config tmux"
git clone https://github.com/gpakosz/.tmux.git >/dev/null 2>&1
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .
echo "${GREEN}[Info]${NC}: Configured Successful"

# echo "Starting to kernel tunning"
# wget -O kernetunning.sh https://gist.githubusercontent.com/soediro/192684163c29b2bf42ea4ce99bcd1793/raw/e5fc9c40f5979d6eeab790361ddbe749c761f158/ubuntu-kernel-tuning.sh
# chmod +x kernetunning.sh && bash kernetunning.sh
# echo "Kernel was Optimized"

# TODO: Secret & Identity Management
# how to get remote token dynamiclly

# TODO: Open Remote Desktop Services
# basic env config

# TODO: Add Glassed Users

# TODO: Build Data Pipeline

# TODO: Self Checking