#!/bin/bash

# Ansible Speed Optimization
# sed  -i  '/^GSSAPI/s/yes/no/g;/UseDNS/d;/Protocol/aUseDNS no' /etc/ssh/sshd_config

# /etc/init.d/sshd restart
# /usr/sbin/sshd reload
# systemctl reload sshd


# Install Building Essential and Basic Tools
echo "Install Building Essential"
sudo apt-get update 
sudo apt-get install -y build-essential tmux git python3 python3-pip


# TODO: Secret & Identity Management
# how to get remote token dynamiclly

# TODO: Open Remote Desktop Services
# basic env config

# TODO: Add Glassed Users

# TODO: Build Data Pipeline

# TODO: Self Checking