#!/bin/bash

#TODO: Check if it was exists env

export RED=$(tput setaf 1 -T linux)
export GREEN=$(tput setaf 2 -T linux)
export YELLOW=$(tput setaf 3 -T linux)
export NC=$(tput sgr0 -T linux)
export HIGHLIGHT=$(tput setab 7 -T linux)

echo "${RED}${HIGHLIGHT}Script Running On the Remote Server Now ${NC}"

# note: also can get by remote services. just add way
# echo "[Info]: Starting to Config SSH"
# sudo sed -i '$ a AcceptEnv TGBOTOKEN' /etc/ssh/sshd_config
# sudo sed -i '$ a AcceptEnv ASKUSER' /etc/ssh/sshd_config
# sudo sed -i '$ a AcceptEnv ASKPASS' /etc/ssh/sshd_config
# sudo sed -i '$ a AcceptEnv ROOTPASS' /etc/ssh/sshd_config
# sudo service sshd restart
# echo "${GREEN}[Info]${NC}: SSH Services Configured"


echo "[Info]: Starting to modifie profile"

# note: if run with sudo. ~ was eq /root/ folder
sed -i '$ a export RED=$(tput setaf 1 -T linux)' /etc/profile
sed -i '$ a export GREEN=$(tput setaf 2 -T linux)' /etc/profile
sed -i '$ a export YELLOW=$(tput setaf 3 -T linux)' /etc/profile
sed -i '$ a export NC=$(tput sgr0 -T linux)' /etc/profile
sed -i '$ a export HIGHLIGHT=$(tput setab 7 -T linux)' /etc/profile

source /etc/profile

echo "${GREEN}[Info]${NC}: Modified Successful"
# Install Building Essential and Basic Tools
echo "[Info]: Starting to install essential"
sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y build-essential sshpass curl tmux git unzip lynx pandoc python3 python3-pip python3-tqdm >/dev/null 2>&1
curl -s https://rclone.org/install.sh | sudo bash >/dev/null 2>&1
echo "${GREEN}[Succeed]${NC}: Installed Successful"

echo "[Info]: Starting to config tmux"
git clone https://github.com/gpakosz/.tmux.git >/dev/null 2>&1
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .
echo "${GREEN}[Succeed]${NC}: Configured Successful"

echo "[Info]: Starting to config sftp"

echo "${GREEN}[Succeed]${NC}: Configured Successful"

# echo "Starting to kernel tunning"
# wget -O kernetunning.sh https://gist.githubusercontent.com/soediro/192684163c29b2bf42ea4ce99bcd1793/raw/e5fc9c40f5979d6eeab790361ddbe749c761f158/ubuntu-kernel-tuning.sh
# chmod +x kernetunning.sh && bash kernetunning.sh
# echo "Kernel was Optimized"

# TODO: Secret & Identity Management
# how to get remote token dynamiclly

# TODO: Open Remote Desktop Services
# basic env config

# TODO: Add Glassed Users

# TODO: Build Data Pipeline

# TODO: Self Checking