#!/bin/bash

install_proxy()
{
echo "Install Proxy"
curl -s -L https://git.io/v2ray.sh > v2ray.sh && chmod +x v2ray.sh && printf '1\n2\ny\ny\n' | sudo ./v2ray.sh
}

if [ ! -z ${1} ]
then
    if [ "${1}" = "install" ]
    then 
        install_proxy
    else
        sudo v2ray ${*:1}
    fi
fi