#!/bin/bash

install_proxy()
{
    echo "${YELLOW}[Info]${NC}: Starting to ${FUNCNAME[0]/_/ }"
    curl -s -L https://git.io/v2ray.sh > v2ray.sh && chmod +x v2ray.sh && printf '1\n2\ny\ny\n' | sudo ./v2ray.sh > /dev/null
    echo "${GREEN}[Info]${NC}: Installed Successful"
}

qr_code()
{
    if ! command -v qrencode &> /dev/null
    then
        echo "[Warning] qrencode could not be found, let's install"
        sudo apt install qrencode > /dev/null
    fi

    qrencode -t ansiutf8  <<< `sudo v2ray url | grep -E vmess://.* | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g'`
    # sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" 
    # remove output color
}

if [ ! -z ${1} ]
then

    if [ "${1}" = "install" ]; then 
        install_proxy
    fi;

    if [ "${1}" = "url" ]
    then
        sudo v2ray url | grep -E vmess://.* | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g'
    elif [ "${1}" = "qr" ]
    then
        qr_code
    else
        sudo v2ray ${*:1}
        exit 1
    fi
    
else 
    install_proxy
fi