#!/bin/bash

install_ruby()
{
    echo "Starting to ${FUNCNAME[0]/_/ }"
} 

install_rust()
{
    echo "Starting to ${FUNCNAME[0]/_/ }"

} 

install_java()
{
    echo "Starting to ${FUNCNAME[0]/_/ }"
    sudo apt-get install -y openjdk-11-jdk openjdk-11-jre
    echo "Installed Successful"
}

install_nodejs()
{
    echo "Starting to ${FUNCNAME[0]/_/ }"
    sudo apt update
    sudo apt install nodejs npm
    echo "Installed Successful"
}

install_docker()
{
    echo "Starting to ${FUNCNAME[0]/_/ }"
    sudo apt-get update >/dev/null
    sudo apt-get install -y ca-certificates curl gnupg lsb-release >/dev/null
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update >/dev/null
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io >/dev/null
    sudo usermod -aG docker $USER
    echo "Installed Successful"
}

if [ ! -z ${1} ]
then
    if [ "${1}" = "ruby" ]; then 
        install_ruby
    fi;

    if [ "${1}" = "rust" ]; then 
        install_rust
    fi;

    if [ "${1}" = "docker" ]; then 
        install_docker
    fi;

    if [ "${1}" = "nodejs" ]; then 
        install_nodejs
    fi;

    if [ "${1}" = "java" ]; then 
        install_java
    fi;


else
    echo "only java/ruby/rust/docker was supported"
fi