#!/bin/bash

install_ruby()
{
    echo "Install Ruby"
} 

install_rust()
{
    echo "Install Rust"

} 

install_docker()
{
    echo "Install Docker"
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
}

if [ ! -z ${1} ]
then
    if [ "${1}" = "ruby" ]; then 
        install_ruby
    fi;

    if [ "${1}" = "rust" ]; then 
        install_rust
    fi;

    if [ "${1}" = "docker" ]; then 
        install_docker
    fi;

else
    echo "only ruby/rust/docker was supported"
fi